### ISSUE TITLE
Divulgar o material para a comunidade

### ISSUE THREAD

**Issue by vmesel** [vmesel/Python-Hands-On#2]
Este será um issue que estará sempre aberto, já que a divulgação não acaba nunca, devemos sempre manter este issue atualizado e permitindo que outras pessoas dêem pull-request!

**Comment by asfelix** [comment]
O projeto foi abandonado?

**Comment by vmesel** [comment]
Não, precisamos de contribuições! Atualmente estou muito ocupado, mas pretendo fazer algo para poder tocar este projeto!
