### ISSUE TITLE
Adicionar conteúdo sobre Docker e Python?

### ISSUE THREAD

**Issue by vmesel** [vmesel/Python-Hands-On#6]

**Comment by crgimenes** [comment]
Acho que Docker merecia um Hands-On só dele... bora criar um Docker-Hands-On?

**Comment by vmesel** [comment]
@crgimenes eu fecho!!

**Comment by crgimenes** [comment]
O ideal seria um especialista em docker manter isso, assim como eu mantenho o de Go e você o de Python, conhece alguém que queira brincar?
